import {
  BrainCircuit,
  Activity,
  Cloud,
  Signal,
  HeartPulse,
  Scale,
  Palette,
  Shield,
  Globe,
  type LucideIcon,
} from "lucide-react";

type Domain = {
  name: string;
  slug: string;
  icon: LucideIcon;
  modules: string[];
  status: string;
};

export const domainData: Domain[] = [
  {
    name: "🧠 System Core",
    slug: "system-core",
    icon: BrainCircuit,
    status: "All systems optimal.",
    modules: [
      "System Configurator",
      "Signal Router",
      "Node Sync Monitor",
      "Vault Operations",
      "Strategist Scripts",
    ],
  },
  {
    name: "📊 Finance & Trading",
    slug: "finance-trading",
    icon: Activity,
    status: "Warning: High volatility detected.",
    modules: [
      "Financial Orchestration",
      "Virtual Debit Suite",
      "Token Economy",
      "Treasury Dashboard",
      "Asset Ledger",
      "Subscription Manager",
      "Crypto-Fiat Bridge",
      "Payment Flow Designer",
      "Fraud Intelligence",
      "Revenue Audit",
      "Trading Suite",
      "Market Analyzer",
      "Backtesting Engine",
      "Portfolio Manager",
      "Exchange Sync",
      "Trading Bots",
      "Live Market Feed",
      "Chart Studio",
      "Signal Visualizer",
      "Risk Panel",
    ],
  },
  {
    name: "☁️ Cloud & DevOps",
    slug: "cloud-devops",
    icon: Cloud,
    status: "Optimal. CI/CD pipeline stable.",
    modules: [
      "Cloud Hub",
      "CI/CD Manager",
      "Firebase Studio",
      "Hosting Manager",
      "Quota Monitor",
      "Secret Vault",
      "Multi-Region Deploy",
      "Runtime Debugger",
      "Env Configurator",
      "Webhook Studio",
    ],
  },
  {
    name: "📡 Telecom & IoT",
    slug: "telecom-iot",
    icon: Signal,
    status: "Warning: Mesh latency increasing.",
    modules: [
      "MVNO Panel",
      "Signal Visualizer",
      "Autonomous Console",
      "Lidar Feed",
      "IoT Manager",
      "Signal Sovereignty",
      "SIM Vault",
      "Mesh Designer",
      "Telecom Monetization",
    ],
  },
  {
    name: "🏥 Medical & Bio",
    slug: "medical-bio",
    icon: HeartPulse,
    status: "Error: Compliance matrix desynced.",
    modules: [
      "Compliance Matrix",
      "Medical Vault",
      "Biometric Router",
      "Neural Interface",
      "Health Sovereignty",
      "DNA Mapper",
      "Biofeedback Studio",
      "Medical AI",
    ],
  },
  {
    name: "⚖️ Legal & Identity",
    slug: "legal-identity",
    icon: Scale,
    status: "Optimal. All roles compliant.",
    modules: [
      "Jurisdictional Router",
      "Wellness Dashboard",
      "Emergency Console",
      "Compliance Engine",
      "Identity Vault",
      "Role Access Control",
      "Signal Citizenship",
      "Legal Router",
      "DAO Console",
      "Consent Ledger",
      "Voting Studio",
      "Compliance Visualizer",
      "Rights Engine",
    ],
  },
  {
    name: "🎨 UI & Experience",
    slug: "ui-experience",
    icon: Palette,
    status: "Optimal. UX feedback positive.",
    modules: [
      "Dashboard Designer",
      "Modular UI",
      "Live Preview",
      "Chart Studio",
      "Theme Manager",
      "Dark Mode",
      "Signal Mapper",
      "Strategist HUD",
      "UX Feedback",
      "Visual AI",
    ],
  },
  {
    name: "🔐 Security & Privacy",
    slug: "security-privacy",
    icon: Shield,
    status: "Warning: Unusual port scan detected.",
    modules: [
      "Vault Console",
      "Encryption Studio",
      "Firewall",
      "Privacy Router",
      "Threat Panel",
      "Lockdown Mode",
      "Secure Transport",
      "Auth Hub",
      "Audit Trail",
      "Backup Engine",
    ],
  },
  {
    name: "🌍 Planetary & Eco",
    slug: "planetary-eco",
    icon: Globe,
    status: "Optimal. Energy consumption nominal.",
    modules: [
      "Solar Router",
      "Gravity Engine",
      "Nature-AI Interface",
      "Planetary Mapper",
      "Eco-Mesh Designer",
      "Resource Console",
      "Climate Vault",
      "Habitat Manager",
      "Energy Engine",
      "Cosmic Visualizer",
    ],
  },
];
